### ISSUE TITLE
UI design for "Available Here"

### ISSUE THREAD

**Issue by lukebp** [HR10Knights/Should-I-Watch-This#4]

**Comment by apedley** [comment]
FREE STREAMING (display names)
 "Hulu"
 "YouTube"

SUBSCRIPTION STREAMING (display names) 
 "Amazon Prime"
 "HBO NOW"
 "Hulu"
 "Showtime"

DIGITAL PURCHASE (display names)
 "Amazon"
 "Google Play"
 "iTunes"
 "YouTube"

ALL
 Amazon
 Amazon Prime
 Google Play
 HBO NOW
 Hulu
 iTunes
 YouTube
